stages:
  - build
  - clean_build

build:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x tl_zigbee_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./tl_zigbee_sdk/  -cleanBuild $ECLIPSE_PROJECT/$ECLIPSE_BUILD_TARGET
    - date

  artifacts:
    paths:
    - "tl_zigbee_sdk/sampleGw_8258/*.bin"
    - "tl_zigbee_sdk/sampleGw_8258/*.lst"
    - "tl_zigbee_sdk/sampleGw_8258/*.elf"

clean_build:
  stage: clean_build
  tags:
    - LINUX
    - TC32
  script:
    - ls -a
    - rm -r * .git*
    - ls -a
  when: always
